entities:
  - display_name: "fruit"
    kind: KIND_MAP
    auto_expansion_mode: AUTO_EXPANSION_MODE_DEFAULT
    entries:
      - value: "apple"
        synonyms: ["apple", "red apple", "green apple"]
      - value: "banana"
        synonyms: ["banana", "yellow banana"]
      - value: "orange"
        synonyms: ["orange", "mandarin", "citrus"]

intents:
  - display_name: "last transaction"
    description: "Provides information about the user's last transaction."
    training_phrases:
      - "What was my last transaction?"
      - "Tell me about my last purchase"
      - "Show me my last order"
      - "Last transaction details"
      - "Can you give me info on my last transaction?"
    priority: 200 
    enable_webhook: false
    is_end_session: false

  - display_name: "account balance"
    description: "Inquires about the user's account balance."
    training_phrases:
      - "What is my account balance?"
      - "Show me my balance"
      - "How much money do I have?"
      - "Account balance"
      - "Can you tell me my balance?"
    priority: 500
    enable_webhook: true
    is_end_session: false

  - display_name: "transaction history"
    description: "Retrieves the user's transaction history."
    training_phrases:
      - "Show me my transaction history"
      - "What are my recent transactions?"
      - "List my transactions"
      - "Transaction history"
      - "Can you provide my transaction details?"
    priority: 300
    enable_webhook: true
    is_end_session: false

  - display_name: "check.order_status_specific"
    description: "Checks the status of a specific order using an order ID."
    parameters:
      - id: "order-id"
        entity_type_display_name: "@sys.any"
        is_list: false
    training_phrases:
      - text_parts:
          - { "text": "What's the status for order number " }
          - { "text": "12345-ABC", "parameter_id": "order-id" }
        repeat_count: 1
      - text_parts:
          - { "text": "Check status for " }
          - { "text": "XYZ-789", "parameter_id": "order-id" }
      - text_parts:
          - { "text": "I need an update on order " }
          - { "text": "OrderNum999", "parameter_id": "order-id" }
      - "Tell me about my order [XYZ000]{@order-id}"
    priority: 5000
    enable_webhook: false
    is_end_session: false

  - display_name: "specify.item_quantity"
    description: "Specifies a quantity for an item."
    parameters:
      - id: "item-name"
        entity_type_display_name: "@sys.any"
        is_list: false
      - id: "number-of-items"
        entity_type_display_name: "@sys.number"
        is_list: false
    training_phrases:
      - text_parts:
          - { "text": "I want " }
          - { "text": "five", "parameter_id": "number-of-items" }
          - { "text": " of the " }
          - { "text": "red apples", "parameter_id": "item-name" }
      - text_parts:
          - { "text": "Can I get " }
          - { "text": "10", "parameter_id": "number-of-items" }
          - { "text": " " }
          - { "text": "bananas", "parameter_id": "item-name" }
          - { "text": "?" }
      - text_parts:
          - { "text": "Set quantity to " }
          - { "text": "22", "parameter_id": "number-of-items" }
    priority: 500000
    enable_webhook: false
    is_end_session: false

  - display_name: "order.fruit"
    description: "User wants to order a fruit using a custom entity"
    parameters:
      - id: "fruit-name"
        entity_type_display_name: "fruit"
        is_list: false
    training_phrases:
      - text_parts:
          - { "text": "I want to order " }
          - { "text": "apple", "parameter_id": "fruit-name" }
      - text_parts:
          - { "text": "Can I get " }
          - { "text": "banana", "parameter_id": "fruit-name" }
      - text_parts:
          - { "text": "Please send me some " }
          - { "text": "orange", "parameter_id": "fruit-name" }
          - { "text": " in a box" }
    priority: 1200
    enable_webhook: false
    is_end_session: false
